### ISSUE TITLE
Why is BothSocksAndTimeout an error?

### ISSUE THREAD

**Issue by icota** [bitcoindevkit/rust-electrum-client#69]
I'm probably missing something but it's not clear to me.

**Comment by afilini** [comment]
It's because we use the `socks` library and it doesn't allow us to establish a connection manually and then wrap a raw `TcpStream` into a socks stream, which is something that we can do for ssl, or to specify a custom timeout.

So for all the other types we can manually open the tcp connection with a custom timeout parameter, and then either use it as-is for plaintext connections or wrap it into an ssl stream. With socks streams we don't have this option, so we thought it's better to explicitly return an error rather than silently ignoring the timeout.

**Comment by icota** [comment]
I understand. Thank you very much @afilini
